"""empty message

Revision ID: 303ef0f02f41
Revises: c703e6b996eb
Create Date: 2022-05-12 21:10:38.092651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303ef0f02f41'
down_revision = 'c703e6b996eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('past_shows_count', sa.Integer(), nullable=False))
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.Integer(), nullable=False))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'upcoming_shows_count')
    op.drop_column('artists', 'past_shows_count')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
