"""empty message

Revision ID: 464d95f3f0ab
Revises: 92f741338d6b
Create Date: 2022-05-18 17:49:20.121712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464d95f3f0ab'
down_revision = '92f741338d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_image_link')
    # ### end Alembic commands ###
