"""empty message

Revision ID: c703e6b996eb
Revises: 23bcfcbf2051
Create Date: 2022-05-09 17:04:44.875466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c703e6b996eb'
down_revision = '23bcfcbf2051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=False))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
